### ISSUE TITLE
An error occured in post-command

### ISSUE THREAD

**Issue by computersarecool** [expez/company-quickhelp#12] opened 2015-04-28 04:52 UTC
I am getting the following error and I do not know how to fix it:

```
Company: An error occurred in post-command                                                                                                                                                                
Company: Front-end company-quickhelp-frontend error "Symbol's function definition is void: pos-tip-hide" on command hide                                                                                  
Error in post-command-hook (company-post-command): (error "Company: Front-end company-quickhelp-frontend error \"Symbol's function definition is void: pos-tip-hide\" on command hide")   
```

**Comment by computersarecool** [comment] 2015-04-28 04:53
The stack trace I get is:

```
Debugger entered--Lisp error: (void-function pos-tip-hide)                                                                                                                                                
  pos-tip-hide()                                                                                                                                                                                          
  company-quickhelp-frontend(hide)                                                                                                                                                                        
  #[0 "\301\300!\207" [hide company-quickhelp-frontend] 2 "\n\n(fn)"]()                                                                                                                                   
  funcall(#[0 "\301\300!\207" [hide company-quickhelp-frontend] 2 "\n\n(fn)"])                                                                                                                            
  company-call-frontends(hide)                                                                                                                                                                            
  #[0 "\306\211^P^Q\306\211^R^S\306\211^T^U\306^V^M\307^V^N\306\211^V^O^V^P\306\211^V^Q^V^R\306^V^S^N^T\203+^@\310^N^T!\210\311\307!\210\312\313!\210\306\314 \210\211\211^V^U\207" [company-backend comp$
  funcall(#[0 "\306\211^P^Q\306\211^R^S\306\211^T^U\306^V^M\307^V^N\306\211^V^O^V^P\306\211^V^Q^V^R\306^V^S^N^T\203+^@\310^N^T!\210\311\307!\210\312\313!\210\306\314 \210\211\211^V^U\207" [company-back$
  company-cancel(unique)                                                                                                                                                                                  
  company--continue()                                                                                                                                                                                     
  company--perform()                                                                                                                                                                                      
  #[0 "`^H\232\204\f^@\304^Y\305 \210)\n\203^T^@\306\307!\207   \247\205,^@\310 \205,^@\311     \304\312p\313 \314 `&^G\211^S\207" [company-point company-idle-delay company-candidates company-timer nil$
  funcall(#[0 "`^H\232\204\f^@\304^Y\305 \210)\n\203^T^@\306\307!\207   \247\205,^@\310 \205,^@\311     \304\312p\313 \314 `&^G\211^S\207" [company-point company-idle-delay company-candidates company-t$
  company-post-command() 
```

**Comment by expez** [comment] 2015-04-28 06:31
This appears to be a duplicate of https://github.com/expez/company-quickhelp/issues/10 

Does anything in there sound familiar?

**Comment by computersarecool** [comment] 2015-04-28 07:23
Unlike #10 I am loading it exactly as the readme says.  All I have in my .emacs is:

```
(company-quickhelp-mode 1)
```

Do I need to install / enable "pos-tip"?

**Comment by computersarecool** [comment] 2015-04-28 07:25
Well, actually I do have it installed. And I think it is being loaded correctly... Any ideas?

**Comment by expez** [comment] 2015-04-28 07:35
You could try an explicit `(require 'pos-tip)` but I doubt that's the problem.  I'm guessing the popup appears as it should, but it's crashing when we try to hide it?  If so, then it's not a problem with the loading of `pos-tip`.

`pos-tip-hide` is an alias for `x-hide-tip`.  I have no idea why that alias doesn't work, but replacing it might help?

``` elisp
(defun company-quickhelp-frontend (command)
  "`company-mode' front-end showing documentation in a `pos-tip' popup."
  (pcase command
    (`post-command (company-quickhelp--set-timer))
    (`hide
     (company-quickhelp--cancel-timer)
     (x-hide-tip))))
```

Put this an emacs-lisp buffer and do `M-x eval-defun <RET>` (with point inside the function) to give this version, which uses `x-hide-tip` explicitly, a try.

**Comment by computersarecool** [comment] 2015-04-28 07:41
I already tried an explicit `(require 'pos-tip)` I noticed no difference.  The pos tip window is not appearing anywhere (at least that I can tell) so I am with you that it is a problem with the loading:

Doing what you said threw the following:

```
Debugger entered--Lisp error: (void-function x-hide-tip)                                                                                                                                                  
  (x-hide-tip)                                                                                                                                                                                            
  eval-region(222 234 t #[257 "\300\242b\210\301\207" [(234) (x-hide-tip)] 2 "\n\n(fn IGNORE)"])  ; Reading at buffer position 240                                                                        
  eval-defun-2()                                                                                                                                                                                          
  eval-defun(nil)                                                                                                                                                                                         
  call-interactively(eval-defun record nil)                                                                                                                                                               
  command-execute(eval-defun record)                                                                                                                                                                      
  execute-extended-command(nil "eval-defun")                                                                                                                                                              
  call-interactively(execute-extended-command nil nil)                                                                                                                                                    
  command-execute(execute-extended-command) 
```

This could be an error with my elisp skills.  I literally just opened a new buffer, typed in exactly what you said and then`M-x eval-defun <RET>`

**Comment by expez** [comment] 2015-04-28 08:21
If you do `M-x describe-function <RET> x-hide-tip <RET>` there's nothing to be found?

If that's the case then, this is probably related to how emacs was built.  It's lacking support for whatever `pos-tip` is delegating to.

**Comment by computersarecool** [comment] 2015-04-28 09:26
I get `[No match]` . Could you elaborate on "related to how emacs was built" or what you think I should do to fix this? (I really appreciate your help here)

**Comment by expez** [comment] 2015-04-28 09:33
@computersarecool when you build emacs from source you can enable or disable certain features.  E.g. you can compile emacs without network support, if that's what you want.  I'm guessing the build setting that's causing this issue is this one: `--with-x-toolkit=no`

How are you installing emacs?  You might have to find another way of installing emacs, if you really want to solve this problem.

**Comment by computersarecool** [comment] 2015-04-28 09:50
Well I do really want to use this feature. I installed it via either macports or homebrew as is listed here: http://www.emacswiki.org/emacs/EmacsForMacOS#toc16

If I install 24.5 using the universal binary, do I have to install all of my other packages?

**Comment by expez** [comment] 2015-04-28 10:00
`brew install --with-x emacs`  should probably do it.

> A version supporting X11 can be built using the --with-x switch. Note that this version will not have all of the features of the Cocoa version; use only if necessary.

This might be an ugly version of emacs.  I don't have a mac myself.

> If I install 24.5 using the universal binary, do I have to install all of my other packages?

The installed packages typically live in `.emacs.d/elpa` or something similar and the `.emacs.d` directory is shared across emacs versions.

**Comment by computersarecool** [comment] 2015-04-28 10:08
Thanks. I will try with the newer 24.5 version and think about using
--with-x

On Tuesday, April 28, 2015, Lars Andersen notifications@github.com wrote:

> brew install --with-x emacs should probably do it.
> 
> A version supporting X11 can be built using the --with-x switch. Note that
> this version will not have all of the features of the Cocoa version; use
> only if necessary.
> 
> This might be an ugly version of emacs. I don't have a mac myself.
> 
> If I install 24.5 using the universal binary, do I have to install all of
> my other packages?
> 
> The installed packages typically live in .emacs.d/elpa or something
> similar and the .emacs.d directory is shared across emacs versions.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/expez/company-quickhelp/issues/12#issuecomment-96997470
> .

## 

Willy Nolan

**Comment by computersarecool** [comment] 2015-04-29 22:56
I should have clarified, I am using Emacs 24.4 on Mac OS X.  It looks like Pos-Tip does not work at all with this configuration.  I would be interested in your opinion here, if you think there are any work arounds. Otherwise I guess the issue can be (unfortunately) closed.

**Comment by expez** [comment] 2015-04-30 06:05
As I mentioned earlier, I think the failure is due to how emacs was built.  If you're willing to build emacs `--with-x` it should work.  If that is indeed why it's failing then there's nothing I can do about it.

Let me know if you decide to give this a try.

**Closed as completed by expez** 2015-04-30 06:05 UTC

**Comment by zhihuiFan** [comment] 2016-02-12 16:08
I have tried this --with-x options, unluckily, it doesn't resolve the issue.

my env:
macos:  10.9.5
emacs:  24.5, installed it with `brew install --with-x emacs`

Here is my .emacs files. 

;; plugin: company-quickhelp
(require 'pos-tip)
(company-quickhelp-mode 1)
(eval-after-load 'company
  '(define-key company-active-map (kbd "M-h") #'company-quickhelp-manual-begin))

Now, I get no error message during startup emacs, but the tooltip still doesn't show the document. 

I tried M-x describe-function <RET> x-hide-tip <RET>,  it can find this function now. 

Before rebuild emacs with --with-x,   I get the error message during startup.  and I didn't try describe-function during that time. 

Thanks

**Comment by zhihuiFan** [comment] 2016-02-12 16:21
I also tried the suggestion according to https://www.reddit.com/r/emacs/comments/3qvyie/getting_postip_working/, 

I added 
(pos-tip-show "aBC")
in my ~/.emacs files. 

Then I got error:

Warning (initialization): An error occurred while loading `/Users/zhifan/.emacs':

error: Window system frame should be used

I startup emacs in a terminal. (Iterm2 in mac)

**Comment by expez** [comment] 2016-02-12 17:03
@zhihuiFan pos-tip doesn't work in the terminal

**Comment by zhihuiFan** [comment] 2016-02-13 00:45
Thanks @expez ,  do you know any other solution for this issue?   company mode + show document when autocomplete + terminal?

**Comment by expez** [comment] 2016-02-15 12:19
@zhihuiFan you could fork this package and replace pos-tip with popup.el which works in the terminal (but has other problems).  popup.el is what auto-complete uses ti display popups (unless pos-tip is available)

**Comment by zhihuiFan** [comment] 2016-02-19 08:11
Thanks @expez .  I found elpy has such ability, see http://elpy.readthedocs.org/en/latest/ide.html.  When I want to see the document, I can type <F1> , it will  show the document in another window.  but the inconvenience is the window will be closed quickly.
