### ISSUE TITLE
Error running timer on emacs 25

### ISSUE THREAD

**Issue by dev-plvlml** [expez/company-quickhelp#5] opened 2015-02-19 11:28 UTC
Hello,
I'm getting an

> Error running timer `company-quickhelp--show': (wrong-type-argument listp default:inherit)

twice in a row when waiting for a tooltip in company, and sometimes I'm getting an

> Error while displaying tooltip: (wrong-type-argument listp default:inherit)

twice in a row in Messages buffer, but can't figure out when. And no tooltips at all.
GNU Emacs 25.0.50.6 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.8), compiled from source.

**Comment by expez** [comment] 2015-02-19 11:42
hi @dev-plvlml, could you do `M-x toggle-debug-on-error <RET>` and see if you get a stacktrace?

**Comment by dev-plvlml** [comment] 2015-02-19 11:53
Thanks @expez,
the backtrace I get is

> Debugger entered--Lisp error: (wrong-type-argument listp default:inherit)
>   face-spec-set-match-display(default:inherit #<frame emacs@m4e5tr0-msi 0x2505e00>)
>   face-spec-choose(((default:inherit font-lock-constant-face)) #<frame emacs@m4e5tr0-msi 0x2505e00>)
>   frame-set-background-mode(#<frame tooltip 0x3419880>)
>   x-show-tip(#("set-advertised-calling-convention is a compiled Lisp function in\n`byte-run.el'.\n\n(set-advertised-calling-convention FUNCTION SIGNATURE WHEN)\n\nSet the advertised SIGNATURE of FUNCTION.\nThis will allow the byte-compiler to warn the programmer when she uses\nan obsolete calling convention.  WHEN specifies since when the calling\nconvention was modified." 0 350 (face (:font "-bitstream-Meslo LG S-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1" :foreground "black" :background "lightyellow"))) #<frame emacs@m4e5tr0-msi 0x2505e00> ((border-width . 1) (internal-border-width . 2) (font . "-bitstream-Meslo LG S-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1") (foreground-color . "black") (background-color . "lightyellow")) 300 -497 -34)
>   pos-tip-show-no-propertize(#("set-advertised-calling-convention is a compiled Lisp function in\n`byte-run.el'.\n\n(set-advertised-calling-convention FUNCTION SIGNATURE WHEN)\n\nSet the advertised SIGNATURE of FUNCTION.\nThis will allow the byte-compiler to warn the programmer when she uses\nan obsolete calling convention.  WHEN specifies since when the calling\nconvention was modified." 0 350 (face (:font "-bitstream-Meslo LG S-normal-normal-normal-_-12-_-_-_-m-0-iso10646-1" :foreground "black" :background "lightyellow"))) nil 198 #<window 3 on *scratch*> 300 496 141 nil nil 1)
>   pos-tip-show("set-advertised-calling-convention is a compiled Lisp function in\n`byte-run.el'.\n\n(set-advertised-calling-convention FUNCTION SIGNATURE WHEN)\n\nSet the advertised SIGNATURE of FUNCTION.\nThis will allow the byte-compiler to warn the programmer when she uses\nan obsolete calling convention.  WHEN specifies since when the calling\nconvention was modified." nil 198 nil 300 80 nil nil 1)
>   company-quickhelp--show()
>   apply(company-quickhelp--show nil)
>   timer-event-handler([t 0 0 500000 nil company-quickhelp--show nil idle 0])

**Comment by expez** [comment] 2015-02-19 12:12
`x-show-tip` is an internal function but this is what `pos-tip` uses to do its thing.  I'm guessing something has changed in emacs 25 which is causing this breakage.

If you want you can take this to the emacs mailing list.  Hopefully this is a bug and not caused by API changes.  In any event, this isn't something I can fix in `company-quickhelp`.

There has been some talk about including a library for creating tooltip popups in emacs 25.  If that's the case I'm going to get rid of `pos-tip`, as it's no longer maintained. Given the hope of such a tooltip library for emacs proper I'm not going to spend any time rewriting `pos-tip` if this problem is caused by API changes.

**Comment by dev-plvlml** [comment] 2015-02-19 12:18
Okay, I got it. Thank you!

**Comment by dev-plvlml** [comment] 2015-02-19 12:35
That's funny but when I did `M-x toggle-debug-on-error <RET>` again to switch the debug off I got all the tooltips.

**Comment by dev-plvlml** [comment] 2015-02-19 12:43
Now my Messages buffer says

> Invalid face attribute :font "-bitstream-Meslo LG S-normal-normal-normal-_-12-_-_-_-m-0-iso10646-1"

each time I get a tooltip.
I've never hardcoded any font setting like this in my init file, my font for Emacs is set in Xresources.

**Comment by expez** [comment] 2015-02-19 14:11
yeah, I get that too (with my own font from Xresources).  I think it's `pos-tip` trying to pass the font information on but something goes wrong, somewhere.

**Comment by expez** [comment] 2015-02-20 06:59
@dev-plvlml modulo some spam about invalid faces int he `*Messages*` buffer, is everything working fine for you now?  Have you tried restarting emacs?  I got the impression this only worked after getting your running emacs into a certain, favorable, state.

**Comment by dev-plvlml** [comment] 2015-02-23 19:00
@expez it's not working fine. I have to toggle debug on and off each time Emacs starts.

**Comment by expez** [comment] 2016-01-28 15:04
Gonna close this as something specific to your setup / machine / apartment.  I've been running emacs 25 myself lately and it seems to work just fine.

**Closed as completed by expez** 2016-01-28 15:04 UTC
