### ISSUE TITLE
Quickhelp tooltip displayed at wrong location

### ISSUE THREAD

**Issue by birkenfeld** [expez/company-quickhelp#2] opened 2015-02-08 15:05 UTC
Using company-quickhelp with [elpy](http://github.com/jorgenschaefer/elpy) and Emacs 25.0.50, I see this behavior when completing:

![snap](https://cloud.githubusercontent.com/assets/144359/6097001/1ae83738-afac-11e4-82ab-de1131f00a3d.png)

**Comment by expez** [comment] 2015-02-09 14:57
damn, that's bad!

What os are you on?  I've only tested this on windows and linux.

Is this specific to `elpy`? Does the quickhelp appear correctly in e.g. `emacs-lisp-mode`?

**Comment by expez** [comment] 2015-02-09 15:20
I managed to reproduce the issue after installing`elpy`.

**Comment by expez** [comment] 2015-02-09 16:02
Figuring out what's causing this seems to be another matter entirely :(

**Comment by expez** [comment] 2015-02-10 18:05
Aight, I've tracked this down to the `company-backend` in elpy itself.  It's doing something that the other backends are not.

`company-tern` looks identical, using the `:async` keyword to avoid blocking emacs, and the popups are aligning just fine using that package.

**Comment by fniessen** [comment] 2015-02-13 21:59
I confirm similar expériences in my Emacs-lisp buffer "Leuven-theme.el" (on GitHub). It began correctly positioned while the word to complete was close to the bottom of the screen. Upon C-l, recentering the word to complete in the middle of the screen, above or once again below, it never was positioned correctly anymore. See video on http://screencast.com/t/w6fdXXCGQsoX.

Calling company-search-candidates (in that ELisp buffer) returns:

Company: An error occurred in auto-begin
Company: Back-end (company-dabbrev-code company-gtags company-etags company-keywords) error "File d:/Users/fni/TAGS does not exist" with args (candidates )

**Comment by expez** [comment] 2015-02-13 22:12
Thanks!

I thought this was limited to `elpy-mode`, but there's apparently more ways to trigger this :angry:

**Comment by fniessen** [comment] 2015-02-13 22:14
Thanks to you for looking into this. Your package is very promising!!

**Comment by expez** [comment] 2015-02-15 09:40
I've rewritten the logic for completion popups.  I'm now unable to reproduce this bug report.  Hopefully I didn't introduce any other problems.  

Please let me know if this is working for everyone else.  I've only tested this on a linux box.

**Comment by birkenfeld** [comment] 2015-02-15 10:02
The location seems good now. However, Emacs hangs up in `company-quickhelp--doc-and-meta` if the doc buffer is empty.

**Comment by birkenfeld** [comment] 2015-02-15 10:05
This loop seems to be never exited:

```
      (while (or (looking-at "\\[back\\]")
                 (looking-at "^\\s-*$"))
        (forward-line -1))
```

**Comment by expez** [comment] 2015-02-15 10:23
@birkenfeld thanks, it should've been

``` elisp
(while (or (= (line-number-at-pos) 1)
                 (looking-at "\\[back\\]")
                 (looking-at "^\\s-*$"))
        (forward-line -1))
```

I've pushed fix.

**Comment by birkenfeld** [comment] 2015-02-15 10:26
Unfortunately, that seems to have made it loop even for nonempty buffers. In this case, with the following contents in the doc buffer:

```
"ask(self, key, ts, time, ttl)

"
```

**Comment by expez** [comment] 2015-02-15 10:52
Yeah, the previous solution was obviously wrong.  I shouldn't code while talking on the phone :p 

``` elisp
(while (and (not (= (line-number-at-pos) 1))
                  (or (looking-at "\\[back\\]")
                      (looking-at "^\\s-*$")))
        (forward-line -1))
```

I've pushed a new version, really hope nobody had the misfortune of pulling a bad version from melpa.

Sorry!

edit: wonder why that indentation is all wrong after being syntax highlighted

**Comment by birkenfeld** [comment] 2015-02-15 10:57
Works like a charm now. Thanks for all your work on this!

**Comment by expez** [comment] 2015-02-15 11:05
Great!

Thanks for helping me solve this! :+1:

**Closed as completed by expez** 2015-02-15 11:05 UTC
Labels: bug, help wanted

**Comment by justmytwospence** [comment] 2015-11-16 21:23
I'm seeing similar behavior to this original issue, should I open a new issue?

**Comment by expez** [comment] 2015-11-17 08:25
@justmytwospence only if you're interested in debugging this issue yourself (with my help).  I've had a few more reports of this happening, this year, but I've never been able to reproduce it reliably, and thus I've been unable to pinpoint the problem.  There's also the likelihood that whatever tweaks are necessary to align stuff on your machine will break it for everyone else (and it seems to work correctly for the vast majority of users now)
