### ISSUE TITLE
Disjointed documentation interface in OS X

### ISSUE THREAD

**Issue by rthoma** [expez/company-quickhelp#42] opened 2016-06-27 05:32 UTC
Hi, I'm experiencing an issue on OS X, and other members of the /r/emacs subreddit are seeing it too.  On the github homepage for company quickhelp it shows [this image,](https://raw.githubusercontent.com/expez/company-quickhelp/master/company-quickhelp.png) in which the documentation panel is basically an extension of the company completion menu. What I get instead (on OS X) is a little more disjointed interface that looks [like this.](http://i.imgur.com/d8elibS.png) It looks like this might be a bug in pos-tip, company quickhelp, or potentially a setup issue. Are there settings I can change that will allow pos-tip to present documentation in a way that better integrates with the company completion menu? I've already left a note for @pitkali on the pos-tip page.

For reference I'm running Emacs 25.1.50 (9.0) on OS X Yosemite (version 10.10.5).

**Comment by expez** [comment] 2016-06-27 09:35
Yeah, I'm aware of this.  It works for me 99% of the time, but sometimes I see what you see too.  I use this on OS X and on Linux and while it happens rarely on Linux I've seen it.

I'm not sure what to do about it.  It works most of the time for me, and when I can't reliable reproduce a problem I can't fix it either.

If you want to get your hands dirty the size and position of the overlay is controlled here:

https://github.com/expez/company-quickhelp/blob/master/company-quickhelp.el#L148-L153

I suspect pos-tip is really just best effort and sometimes pos-tip fails to deliver due to collision detection or whatever.

**Comment by pitkali** [comment] 2016-06-27 11:21
Interesting. When you see that on linux, do you also see a default system tooltip ignoring Emacs' face and colour settings?

Because as far as I can tell, the first problem with the reported issue here is that on mac `(x-gtk-use-system-tooltips nil)` will have no effect, and so the stock Emacs will use system tooltip, totally messing around with what the tooltip looks like. I have yet to investigate what's going on with the positioning, though.

**Comment by expez** [comment] 2016-06-27 11:28
> When you see that on linux, do you also see a default system tooltip ignoring Emacs' face and colour settings?

No, I get a sense it happens because pos-tip feels there isn't room / something is in the way at the right position.

**Comment by pitkali** [comment] 2016-06-27 11:30
That would probably deserve its own, separate investigation, I suppose. All in good time.

**Comment by rthoma** [comment] 2016-06-28 05:03
Hi guys, thanks for your prompt replies. The point that @pitkali raised is interesting. I didn't know that OS X uses a native tooltip. I would be perfectly happy with a tooltip that didn't match the theme provided it showed up in the right place.

I first started thinking about this because I wanted to recreate the functionality that I saw in [this video](https://youtu.be/mflvdXKyA_g?t=55) by Baris Yuksel. I realized later that this was a previous version of elpy that used autocomplete, but I still like the behavior.

Thanks to @expez for pointing out the section of the company-quickhelp code that controls the position of the overlay. I'm new to elisp and Emacs, but if I have some down time this weekend I might fiddle with this section of code on my mac and see what happens. 

Would it make sense to use a wrapper like (when (eq system-type 'darwin) ... ) in this case to keep any changes from messing with Linux and Windows?

**Comment by pitkali** [comment] 2016-06-28 08:54
In short, no.

Firstly, I didn't have time to confirm this yesterday, but the problem is unlikely to be mac as an operating system (i.e., `'darwin`), but rather one of the 2 UI toolkit implementations used on it, so `(when (eq window-system 'ns) ...)`. Mac-port (which at least used to be distinguishable with `window-system` being `'mac`) is fundamentally different, to the best of my memory, having originated from Carbon emacs, which predates the `'ns` toolkit. I specifically remember it having a different tooltip implementation (i.e., different implementation of `x-show-tooltip` emacs C function that you can see pos-tip using eventually to actually show the tooltip). It should not be assumed it will behave the same way here.

Secondly, I would very much prefer to hide such differences between various toolkits in pos-tip. This may not be feasible in an acceptable way, depending on the actual root cause, but that would be the ideal scenario.

Nonetheless, if the issue is not fixed by the weekend, feel free to see if you can correct coordinates. If you find a way, it is likely to be useful as diagnostic information, helping us better understand what's going on.

**Comment by expez** [comment] 2016-08-24 12:57
@pitkali can I close this as a problem with pos-tip?

**Comment by pitkali** [comment] 2016-08-24 14:02
It's safe to assume that the problem does not lie with company-quickhelp, as then it should happen on all the platforms.

In short, yes.

**Closed as completed** 2016-08-24 15:08 UTC
